### ISSUE TITLE
Not familiar with node.js - installation issue

### ISSUE THREAD

**Issue by developerPaul** [horatio-sans-serif/linode-api#3]
# npm install linode-api

npm http GET https://registry.npmjs.org/linode-api
npm http 200 https://registry.npmjs.org/linode-api

npm ERR! Error: No compatible version found: linode-api
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/lib/nodejs/npm/lib/cache.js:486:10)
npm ERR!     at next_ (/usr/lib/nodejs/npm/lib/cache.js:436:17)
npm ERR!     at next (/usr/lib/nodejs/npm/lib/cache.js:413:44)
npm ERR!     at /usr/lib/nodejs/npm/lib/cache.js:406:5
npm ERR!     at saved (/usr/lib/nodejs/npm/lib/utils/npm-registry-client/get.js:151:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 3.5.2-3.fc17.x86_64
npm ERR! command "nodejs" "/bin/npm" "install" "linode-api"
npm ERR! cwd /root
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.19
npm ERR! message No compatible version found: linode-api
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

**Comment by horatio-sans-serif** [comment]
Sorry, I haven't used Node in 2+ years now...
